[{title:"X Collection",
img:"https://github.com/phoopyone/porn/raw/main/allsite.png",
link:"https://www.apkguidemm.net/lee/vids.php?xitem1",
decc: ""
},{title:"Telegram",
img:"https://github.com/phoopyone/porn/raw/main/telegram.jpg",
link:"https://t.me/mmdarktv",
decc: ""
},
{
title: "star pay mal",
img: "https://github.com/phoopyone/porn/raw/main/rate%20(2).png",
link: "https://play.google.com/store/apps/details?id=com.apyar.kallkarandroid",
decc: "Video Des"
}]
