[{title:"Football Live App",
img:"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg12pYyzi1jyv_DaKIXjE8sAc3vGGbyQZay4ngNUCNJMOimooFsJ7YkG2n7GUvTPJfRVYYhiOY7FRbMX3Q5eSP_pl98TNkl_cMYQ6QDf9htrZGvNOhVthLCXJXaxt0OXoHs-0dHZNZ3mhzdkKckDlBHncGDKMg6VblF7dEyU4UKb2_GdjUQqSOO3rSg/s320/fblivetwo.png",
link:"https://play.google.com/store/apps/details?id=com.mmad.kbox",
decc: ""
},
{title:"Football Live App",
img:"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjYwS6-SC9tsipo4Hd47B4w_3TBidygx-7wQL5WxtYTDb-vVDqnih8Sg-ZQl223oAtiHrltN9bJ1jj2iSACWKJfCGDYIMCP1Nz1fZkVQI6o9kM6UIlyniHFSHT-9bj78QdyB5hMC4sUFJcCSIjXi5EinHkRKEqPqQu5ocJCL8h-Y-ijAcyFS-M5TBwQ/s320/wcup.png",
link:"https://play.google.com/store/apps/details?id=com.mmad.kbox",
decc: ""
},
{
title: "Latest App",
img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhJ6-fmLn_h5Z7DDkfoMuQ21rsZLMMs1V1x-BVxLVvwgMv_iZ5fnX5ef3CIWhNSnOvhp8-clYan2VyNwP0IIBODMztZxvlKeMURElRqctsdKRDsHdbNce5zmYEwLgOWwkzH3ePHL9eqNeqWGMk5w81ZIKx9JB7kjyqSltH0NiaqFMAN0QP52vmbYS_C/s320/1665364620778.png",
link: "https://play.google.com/store/apps/details?id=com.apyar.kallkarandroid",
decc: "Video Des"
}
,{title:"Telegram",
img:"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjkSOdu3oCSS79VlXHTqF4RtniNSQo7yzb0hWEvJnhkAqT5JUwT0ZWaR9fZrKV2M338AcDXUrskEnEtUBO05-Fp94eLgMe1ExK_LEO4rjiFuv4L2ocM4oxCdxzyTQ_ZrBin27h2yJsOEV-HyALEAO3KRhQIIylzVPOsczqlyLTFORsVOm-UfkoKKo1S/s320/telegram.jpg",
link:"https://t.me/msubdark",
decc: ""
},
{
title: "star pay mal",
img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiEyT_nXidv_sUHh_5HMVXfZqmFyhIRhZd3LllM4rXSKaeKfvtNZ61A3osIfQEgatm48Uxn78QmvSNBuy3sAsH6OdX7jPJDr1NS5D2Hkd7qf8nHkCRsCpHO9IWDLSu5ijD232ayzBMaHqbxtPTuWt8AxfPYNe9cIee_b-4yqBFcI4gGIkJl_D_ITEBD/s320/rate%20(2).png",
link: "https://play.google.com/store/apps/details?id=com.korea.allkar",
decc: "Video Des"
}]
